-- ═══════════════════════════════════════════════════════════════════
--  EnMartinez.com — Tabla de mensajes de contacto
--  Generado: 6 de agosto de 2026
--
--  QUÉ RESUELVE:
--  El formulario de contacto.html apuntaba a un endpoint viejo de
--  Formspree (`/f/enmartinez1@outlook.com`) que ya no existe: todo lo
--  que la gente escribía se perdía sin dejar rastro y sin avisar.
--
--  Ahora el mensaje se guarda aquí, igual que las solicitudes de
--  registro, y aparece en el panel de administrador.
--
--  CÓMO USARLO:
--    Supabase → proyecto LaPastora → SQL Editor → New query
--    → pegar TODO este archivo → Run.
--
--  Es seguro correrlo más de una vez.
-- ═══════════════════════════════════════════════════════════════════


-- ═══════════════════════════════════════════════════════════════════
--  PARTE 1 — La tabla
-- ═══════════════════════════════════════════════════════════════════

create table if not exists public.mensajes (
  id        bigint generated by default as identity primary key,
  nombre    text not null,
  email     text not null,
  mensaje   text not null,
  estado    text not null default 'nuevo',
  creado_en timestamptz not null default now()
);

-- Solo estos tres valores son válidos, vengan de donde vengan.
alter table public.mensajes drop constraint if exists mensajes_estado_valido;
alter table public.mensajes add constraint mensajes_estado_valido
  check (estado in ('nuevo','leido','archivado'));

-- El panel lista por fecha descendente; el trigger consulta por fecha
-- en cada inserción. Sin índice, ambas cosas empeoran conforme crece.
create index if not exists mensajes_creado_en_idx
  on public.mensajes (creado_en desc);


-- ═══════════════════════════════════════════════════════════════════
--  PARTE 2 — Row Level Security
--  Mismo criterio que `solicitudes`: cualquiera escribe, solo Pedro lee.
-- ═══════════════════════════════════════════════════════════════════

alter table public.mensajes enable row level security;

-- Cualquiera puede ENVIAR un mensaje (el formulario es público)...
drop policy if exists "envio publico de mensajes" on public.mensajes;
create policy "envio publico de mensajes"
  on public.mensajes for insert
  to anon, authenticated
  with check (true);

-- ...pero NADIE anónimo puede leerlos. Sin política de select para `anon`,
-- la tabla es un buzón: entra correo, no sale.
drop policy if exists "admin lee mensajes" on public.mensajes;
create policy "admin lee mensajes"
  on public.mensajes for select
  to authenticated
  using (public.es_admin_enmartinez());

drop policy if exists "admin actualiza mensajes" on public.mensajes;
create policy "admin actualiza mensajes"
  on public.mensajes for update
  to authenticated
  using (public.es_admin_enmartinez())
  with check (public.es_admin_enmartinez());

drop policy if exists "admin elimina mensajes" on public.mensajes;
create policy "admin elimina mensajes"
  on public.mensajes for delete
  to authenticated
  using (public.es_admin_enmartinez());


-- ═══════════════════════════════════════════════════════════════════
--  PARTE 3 — Validación y freno de inundación
--  Calcado del trigger de `solicitudes`, que ya se probó con
--  inserciones maliciosas reales.
-- ═══════════════════════════════════════════════════════════════════

create or replace function public.validar_mensaje_publico()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  ultimo_minuto int;
  ultima_hora   int;
  mismo_correo  int;
begin
  -- ── a) Todo mensaje nuevo nace sin leer ──
  -- Aunque el remitente mande estado='archivado', aquí se ignora.
  new.estado    := 'nuevo';
  new.creado_en := now();

  -- ── b) El admin no pasa por los frenos de abajo ──
  if public.es_admin_enmartinez() then
    return new;
  end if;

  -- ── c) Campos mínimos con sentido ──
  if new.nombre is null or length(trim(new.nombre)) < 2 then
    raise exception 'Escribe tu nombre.'
      using errcode = 'check_violation';
  end if;

  if new.email is null or new.email !~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$' then
    raise exception 'El correo no tiene un formato válido.'
      using errcode = 'check_violation';
  end if;

  if new.mensaje is null or length(trim(new.mensaje)) < 10 then
    raise exception 'El mensaje es muy corto. Cuéntanos un poco más.'
      using errcode = 'check_violation';
  end if;

  -- ── d) Límites de longitud ──
  -- Evita que alguien mande un texto de 10 MB por campo.
  if length(coalesce(new.nombre,''))  > 120  or
     length(coalesce(new.email,''))   > 160  or
     length(coalesce(new.mensaje,'')) > 2000
  then
    raise exception 'Uno de los campos excede el largo permitido.'
      using errcode = 'check_violation';
  end if;

  -- ── e) Freno de inundación ──
  -- El sitio recibe unos pocos mensajes al día. Estos topes no estorban
  -- al uso normal, pero cortan en seco un script que intente meter miles.
  select count(*) into ultimo_minuto
    from public.mensajes where creado_en > now() - interval '1 minute';
  if ultimo_minuto >= 5 then
    raise exception 'Demasiados mensajes seguidos. Espera un minuto e intenta de nuevo.'
      using errcode = 'check_violation';
  end if;

  select count(*) into ultima_hora
    from public.mensajes where creado_en > now() - interval '1 hour';
  if ultima_hora >= 40 then
    raise exception 'Demasiados mensajes en la última hora. Intenta más tarde.'
      using errcode = 'check_violation';
  end if;

  -- ── f) Tope por correo ──
  select count(*) into mismo_correo
    from public.mensajes
    where lower(email) = lower(trim(new.email))
      and creado_en > now() - interval '1 hour';
  if mismo_correo >= 3 then
    raise exception 'Ya nos escribiste varias veces. Te respondemos pronto.'
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_validar_mensaje_publico on public.mensajes;
create trigger trg_validar_mensaje_publico
before insert on public.mensajes
for each row execute function public.validar_mensaje_publico();


-- ═══════════════════════════════════════════════════════════════════
--  LISTO
--
--  Para que además te llegue un correo cuando entre un mensaje:
--
--  1) Vuelve a desplegar la Edge Function `notify-nueva-solicitud`
--     (Supabase → Edge Functions → la función → pegar el index.ts nuevo
--     → Deploy). Ya distingue si el aviso viene de `solicitudes` o de
--     `mensajes` y arma un correo distinto para cada uno.
--
--  2) Database → Webhooks → Create a new hook
--       Name: aviso-nuevo-mensaje
--       Table: mensajes · Events: INSERT · Type: HTTP Request · Method: POST
--       URL: la misma de la Edge Function
--       Header: Authorization = Bearer TU_SERVICE_ROLE_KEY
--     (idéntico al webhook que ya tienes para solicitudes, solo cambia
--      la tabla y el nombre)
-- ═══════════════════════════════════════════════════════════════════
