-- ═══════════════════════════════════════════════════════════
--  EnMartinez.com — Esquema de base de datos para Supabase
--  Pegar completo en: Supabase → SQL Editor → New query → Run
-- ═══════════════════════════════════════════════════════════

-- ── Tabla de negocios publicados ──
create table public.negocios (
  id          bigint generated by default as identity primary key,
  nombre      text not null,
  categoria   text not null,
  cat_label   text,
  icono       text default '🏪',
  descripcion text,
  direccion   text,
  telefono    text,
  whatsapp    text,
  horario     text,
  servicios   jsonb default '[]'::jsonb,
  pago        jsonb default '[]'::jsonb,
  facebook    text default '',
  web         text default '',
  destacado   boolean default false,
  lat         double precision,
  lng         double precision,
  creado_en   timestamptz default now()
);

-- ── Tabla de solicitudes del formulario de registro ──
create table public.solicitudes (
  id                 bigint generated by default as identity primary key,
  estado             text default 'pendiente',  -- pendiente | aprobado | rechazado
  nombre             text not null,
  categoria          text,
  direccion          text,
  descripcion        text,
  horario            text,
  telefono           text,
  whatsapp           text,
  facebook           text,
  web                text,
  servicios          text,
  metodospago        text,
  solicita_destacado boolean default false,
  -- datos privados del propietario
  propietario        text,
  email_contacto     text,
  celular_contacto   text,
  creado_en          timestamptz default now()
);

-- ── Seguridad (RLS): qué puede hacer cada quien ──
-- IMPORTANTE: el proyecto es compartido (LaPastora), por eso las reglas de
-- administración están amarradas a UN correo específico, no a cualquier
-- usuario autenticado del proyecto.
alter table public.negocios    enable row level security;
alter table public.solicitudes enable row level security;

-- Función auxiliar: ¿el usuario conectado es el admin de EnMartinez?
create or replace function public.es_admin_enmartinez()
returns boolean
language sql
stable
as $$
  select coalesce(auth.jwt() ->> 'email', '') = 'pedromanterola2@gmail.com';
$$;

-- Cualquiera puede LEER los negocios (es un directorio público)
create policy "lectura publica de negocios"
  on public.negocios for select
  to anon, authenticated
  using (true);

-- Solo Pedro puede crear/editar/borrar negocios
create policy "admin gestiona negocios"
  on public.negocios for all
  to authenticated
  using (public.es_admin_enmartinez())
  with check (public.es_admin_enmartinez());

-- Cualquiera puede ENVIAR una solicitud (formulario público)...
create policy "envio publico de solicitudes"
  on public.solicitudes for insert
  to anon, authenticated
  with check (true);

-- ...pero solo Pedro puede verlas y gestionarlas
create policy "admin lee solicitudes"
  on public.solicitudes for select
  to authenticated
  using (public.es_admin_enmartinez());

create policy "admin actualiza solicitudes"
  on public.solicitudes for update
  to authenticated
  using (public.es_admin_enmartinez())
  with check (public.es_admin_enmartinez());

create policy "admin elimina solicitudes"
  on public.solicitudes for delete
  to authenticated
  using (public.es_admin_enmartinez());

-- ── Índices para búsquedas y filtros ──
create index negocios_categoria_idx  on public.negocios (categoria);
create index negocios_destacado_idx  on public.negocios (destacado);
create index solicitudes_estado_idx  on public.solicitudes (estado);

-- ── Los 13 negocios actuales ──
insert into public.negocios (nombre, categoria, cat_label, icono, descripcion, direccion, telefono, whatsapp, horario, servicios, pago, facebook, web, destacado, lat, lng) values
('Taquería El Buen Taco','restaurantes','🍽️ Restaurantes','🌮','Los mejores tacos de canasta y al pastor de Martínez. Más de 20 años de tradición familiar sirviendo a la comunidad con sabores auténticos veracruzanos.','Av. Insurgentes 45, Centro','232 123 4567','2321234567','Lun–Sáb 8:00–20:00','["Tacos al pastor","Tacos de canasta","Tortas","Para llevar","A domicilio"]','["Efectivo","Transferencia"]','https://facebook.com','',true,20.0731,-97.0527),
('Farmacia San Francisco','salud','🏥 Salud','💊','Medicamentos de patente y genéricos, vitaminas, artículos de salud y cuidado personal. Contamos con médico de guardia sin costo y servicio a domicilio disponible.','Calle Hidalgo 12, Centro','232 234 5678','2322345678','Lun–Dom 8:00–22:00','["Medicamentos genéricos","Vitaminas","Médico sin costo","Inyecciones","Servicio a domicilio"]','["Efectivo","Tarjeta","Transferencia"]','','',false,20.0715,-97.0510),
('Abarrotes La Esperanza','abarrotes','🛒 Abarrotes','🛒','Abarrotes completos, frutas, verduras y productos de limpieza. Manejamos precios de mayoreo para negocios y familias. Surtido fresco todos los días.','Blvd. Adolfo Ruiz Cortines 88','232 345 6789','2323456789','Lun–Sáb 7:00–21:00','["Abarrotes","Frutas y verduras","Limpieza","Precios mayoreo","Refrescos y agua"]','["Efectivo","Transferencia"]','','',false,20.0725,-97.0535),
('Hotel Plaza Martínez','hoteles','🏨 Hoteles','🏨','Hotel céntrico con 30 habitaciones equipadas, WiFi de alta velocidad, estacionamiento gratuito y aire acondicionado. Ideal para viajeros de negocios y turistas.','Calle 20 de Noviembre 5, Centro','232 456 7890','2324567890','Recepción 24 hrs','["WiFi gratis","Estacionamiento","Aire acondicionado","TV cable","Desayuno incluido"]','["Efectivo","Tarjeta","Transferencia"]','https://facebook.com','',true,20.0718,-97.0520),
('Taller Mecánico García','talleres','🔧 Talleres','🔧','Servicio mecánico general para todo tipo de vehículos. Especialistas en frenos, suspensión, afinaciones y diagnóstico computarizado. 15 años de experiencia.','Carretera a Tlapacoyan km 2','232 567 8901','2325678901','Lun–Sáb 8:00–18:00','["Afinación","Frenos","Suspensión","Diagnóstico computarizado","Cambio de aceite"]','["Efectivo","Transferencia"]','','',false,20.0735,-97.0515),
('Salón de Belleza Vanity','belleza','💇 Belleza','💇','Salón de belleza profesional con tratamientos capilares, cortes modernos, tintes, manicure y pedicure. Trabajamos con cita previa para brindarte mejor atención.','Av. Veracruz 67, Col. Centro','232 678 9012','2326789012','Mar–Sáb 9:00–19:00','["Corte y peinado","Tintes","Manicure","Pedicure","Tratamientos capilares"]','["Efectivo","Transferencia"]','https://facebook.com','',false,20.0722,-97.0525),
('Ferretería El Tornillo','construccion','🏗️ Construcción','🏗️','Ferretería y materiales de construcción con el surtido más completo de la región. Herramientas, tornillería, pinturas, tablarroca y más. Asesoría personalizada.','Calle Morelos 34, Centro','232 789 0123','2327890123','Lun–Sáb 8:00–19:00','["Materiales de construcción","Herramientas","Pinturas","Tornillería","Instalación eléctrica"]','["Efectivo","Tarjeta","Transferencia","Crédito"]','','',false,20.0710,-97.0530),
('Veterinaria Patitas','veterinarias','🐾 Veterinarias','🐾','Clínica veterinaria con médico titulado para consultas, vacunas, cirugías y estética de mascotas. Atendemos perros, gatos y animales de granja. Urgencias disponibles.','Av. Juárez 101, Col. Centro','232 890 1234','2328901234','Lun–Vie 9:00–18:00, Sáb 9:00–14:00','["Consultas","Vacunación","Cirugías","Estética","Urgencias"]','["Efectivo","Tarjeta","Transferencia"]','https://facebook.com','',false,20.0740,-97.0518),
('Taxis Martínez Express','transporte','🚕 Transporte','🚕','Servicio de taxi local y foráneo las 24 horas del día. Viajes seguros a Xalapa, Poza Rica, Tuxpan y aeropuerto. Unidades cómodas y choferes de confianza.','Base: Av. Independencia 23, Centro','232 901 2345','2329012345','24 horas, los 365 días','["Taxi local","Viajes foráneos","Aeropuerto","Xalapa / Poza Rica","Grupos"]','["Efectivo","Transferencia"]','','',false,20.0728,-97.0512),
('Panadería El Trigal','panaderias','🥐 Panaderías','🥐','Panadería artesanal con hornada fresca dos veces al día. Pan de dulce, teleras, bolillos, pasteles y repostería para eventos. Sabor casero de toda la vida.','Calle Zaragoza 78, Col. Centro','232 012 3456','2320123456','Lun–Dom 7:00–21:00','["Pan de dulce","Teleras y bolillos","Pasteles","Repostería","Pedidos especiales"]','["Efectivo"]','','',false,20.0720,-97.0528),
('Banco BBVA Martínez','bancos','🏦 Bancos','🏦','Sucursal bancaria con cajeros automáticos, ventanilla de servicio, créditos personales y empresariales, y atención a empresas. Estacionamiento disponible.','Av. Insurgentes 10, Centro','800 226 2663','','Lun–Vie 9:00–16:00','["Cajero automático","Cuentas de ahorro","Créditos","Transferencias","Atención empresarial"]','["N/A"]','','https://bbva.mx',false,20.0717,-97.0523),
('Despacho Contable Ramírez','profesionales','⚖️ Profesionales','📋','Despacho contable y fiscal con más de 10 años de experiencia. Declaraciones de impuestos, nómina, contabilidad mensual y asesoría para personas físicas y morales.','Calle Allende 56, Planta Alta','232 111 2233','2321112233','Lun–Vie 9:00–18:00','["Declaraciones SAT","Contabilidad","Nómina","Facturación CFDI","Asesoría fiscal"]','["Efectivo","Transferencia"]','','',false,20.0724,-97.0519),
('Empacadora Cítricos del Norte','agroindustria','🍊 Agroindustria','🍊','Empresa empacadora y distribuidora de cítricos de la región. Naranja, mandarina y limón en presentaciones para mayoristas, supermercados y exportación.','Carretera Nautla km 4.5','232 222 3344','2322223344','Lun–Sáb 7:00–17:00','["Empaque de naranja","Mandarina","Limón","Venta mayoreo","Exportación"]','["Efectivo","Transferencia","Crédito"]','','',false,20.0755,-97.0500);
